# Deploy Apps application with Liveness and Readiness Probe without pvc
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: dev
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      serviceAccountName: hello-world
      imagePullSecrets:
        - name: helloworldsudigital
      containers:
        - name: hello-world
          image: helloworldsudigital.azurecr.io/hello-world
          ports:
            - name: httpport
              containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: httpport
            initialDelaySeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /
              port: httpport
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources:  
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
