# Deploy Apps application with Liveness and Readiness Probe without PVC
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: dev
  labels:
    app: hello-world
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      serviceAccountName: hello-world
      containers:
        - name: hello-world
          image: "{{ .Values.image.repository }}"
          ports:
            - name: httpport
              containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: httpport
            initialDelaySeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /
              port: httpport
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "{{ .Values.resources.limits.cpu }}"
              memory: "{{ .Values.resources.limits.memory }}"
            requests:
              cpu: "{{ .Values.resources.requests.cpu }}"
              memory: "{{ .Values.resources.requests.memory }}"
